### ISSUE TITLE
Ignore embed blocks's context for specific pages in the backlinks pane

### ISSUE THREAD

**Issue by yoghurtdewdew** [ivan-lednev/better-search-views#10]
Ignore specific pages or ignore embed blocks's context for specific pages in the backlinks pane, such as pages or folder notes as a catalog, as well as pages from daily notes viewer plugin.
<img width="586" alt="image" src="https://github.com/Quorafind/Obsidian-Daily-Notes-Editor/assets/63794438/689e130b-58d2-4b5a-ba96-70d656ee7654">

**Comment by ivan-lednev** [comment]
Hello, @yoghurtdewdew,

I might not totally get what you're describing, but excluding files from search results is already present in Obsidian. Here is how you can exclude a folder or any path from search results:
![image](https://github.com/ivan-lednev/better-search-views/assets/41428836/1398498f-8a18-457c-925d-3b93cbc9f1c5)

**Comment by yoghurtdewdew** [comment]
Hi! Thanks for your reply.
I mean to exclude context of long embed things from backlinks pane instead of the search results.
However, recently, I  was glad to tell this: I found this has been solved, and I don't know how it worked out.

**Comment by ivan-lednev** [comment]
Closing the issue, since it's been resolved by itself.
