### ISSUE TITLE
missing documentation / how to use this.

### ISSUE THREAD

**Issue by paxsali** [ivan-lednev/better-search-views#15]
Hello there,

how do you use this plugin?

On the README.MD page I only see some prepared views / search queries.

How do you actually perform a search / query from an existing document and what's the syntax.

I'm missing technical documentation and sorry, but the GIFs are nice, but not really self-explanatory.

Thank you.

**Comment by ivan-lednev** [comment]
Hello, @paxsali,

There is no special syntax or custom views. As it says in readme, the plugin **patches** Obsidian's search/backlink/query functionality, so to use the plugin:
1. Install it
2. Reload Obsidian
3. Search for stuff with Obsidian's built-in search OR open the built-in backlinks panel OR write an in-document query with Obsidian's syntax

**Comment by paxsali** [comment]
I wanna know how to use embedded queries.

It's the fourth screenshot from the README.MD (starting from the top), under the heading "embedded queries".

In this screenshot, it appears to be a regular document with headings and a task list,... and below that what appears to be a "query".

My assumption was that it is a customizable version of what "Influx" does automatically with backlinks.

In this example there is some text in the documents `"tag:#initial-release"`.

I tried typing it after restarting Obsidian (after I installed better-search-views), but nothing happens.

My assumption was that better-search-views can be used like dataview or tasks for custom searches with context.

Apparently I am either wrong, or it's not documented how to create a document like in screenshot 4, "embedded queries".

Can you elaborate?

**Comment by ivan-lednev** [comment]
Oh, I see. What you're referring to is embedding global search results into a page. Check out Obsidian docs on this: https://help.obsidian.md/Plugins/Search#Embed%20search%20results%20in%20a%20note

**Comment by paxsali** [comment]
I see now. So basically the "embedding" part (what I refer to as dataview- or task-like...) is actually an Obsidian builtin functionality (that I apparently missed).

And the particular display / layout is just the patched version of the Obsidian results view.

That's so much clearer now.

Thanks.
