### ISSUE TITLE
Feature request: remember sort order of the linked references

### ISSUE THREAD

**Issue by cakechaser** [ivan-lednev/better-search-views#17]
Not sure if it would be possible to do, since it's part of the core "Backlinks" plugin, but it would be great at have an option to remember the sort order of the references.

Right now it defaults to "File Name (A to Z)" after Obsidian restart, but I often use "File Name (Z to A)" and have to manually change it every time.

Thanks!

**Comment by ivan-lednev** [comment]
Hello, @cakechaser,

The plugin doesn't interact with sorting in any way. The behavior you described comes from Obsidian itself, so it's a good idea to create a feature request at the official forum: https://forum.obsidian.md/c/bug-reports/7

**Comment by cakechaser** [comment]
@ivan-lednev, thanks, understood.
I see that this request already exists, so I will close this issue:
https://forum.obsidian.md/t/retain-remember-status-of-backlinks-in-document/20341/27
