### ISSUE TITLE
[BUGS] Get black screen when click backlinks mobile

### ISSUE THREAD

**Issue by l2eused** [ivan-lednev/better-search-views#27]
when using this plugin and click backlinks to some document. it will results as black screen.

Obsidian mobile v1.4.16
Plugin v0.2.2
Android 13 aosp based rom

**Comment by oldjove** [comment]
Same here.

**Comment by bitclick** [comment]
cannot reproduce this
obsidian v 1.5.12
plugin v.0.2.2
android 13 aosp based
