### ISSUE TITLE
Is it possible to publish  query result using obsidian publish or equivalent one like quartz?

### ISSUE THREAD

**Issue by rao10** [ivan-lednev/better-search-views#35]
I put tags in callouts and tried to query 
```query
block: #maya AND #Inca
```

and it works in Obsidian editor preview, but when I publish it with obsidian publish, it doesn't work.  I copied   main.js and styles.css into  Obsidian vault's ( publish.js and publish.css) . But it couldn't show result or render. 

Any suggestion to make this  publish functionality make it work? If it doesn't work for publish, I appreciate a reply

**Comment by ivan-lednev** [comment]
Hello,

To be honest, I don't know whether default Obsidian queries work on publish at all. My guess is that they do not, in which case, my plugin is not going to work either.

**Comment by rao10** [comment]
Thank you for the clarification.
