### ISSUE TITLE
little but important improvement

### ISSUE THREAD

**Issue by mr-d-r** [ivan-lednev/better-search-views#36]
thank you for the cool plugin.

i like obsidian, but it gives me a huge headache when i search several words.
by default obsidian joins search words with OR
and I have to enclose them with quotation marks to let search with AND.
his is extremely irritating and disappointing for me.

could you please make an option in your plugin "Autoenclose search string"?
i believe it will be useful for a lots of people

regards

**Comment by ivan-lednev** [comment]
Hello,

This plugin doesn't deal with the search engine. It only changes the representation of the search results. So this most certainly is outside the scope of the plugin and won't be implemented.
