### ISSUE TITLE
Not working on Obsidian Version 1.7.4 !!!

### ISSUE THREAD

**Issue by meomuop98** [ivan-lednev/better-search-views#39]
This Plug-in is not working on Obsidian Version 1.7.4 anymore, neither desktop nor mobile (only work on 1.6.7 and earlier verions). Please fix this, thank you so much.

**Comment by meomuop98** [comment]
![image](https://github.com/user-attachments/assets/567021bd-2892-44f1-9e79-71bb718efc5e)
You have to disable the "Show more Context" function to keep it working !

**Comment by bhopmann** [comment]
For me disabling "Show more context" doesn't work (it was even deactivated before).

**Comment by meomuop98** [comment]
> For me disabling "Show more context" doesn't work (it was even deactivated before).

You have to search something in the search box and then it will work again

**Comment by bhopmann** [comment]
> > For me disabling "Show more context" doesn't work (it was even deactivated before).
> 
> You have to search something in the search box and then it will work again

Thank you, with doing a quick search it is working now.

**Comment by meomuop98** [comment]
here is how to fix it: update to version 1.7.5 !!!

**Comment by ivan-lednev** [comment]
Duplicate of #40
