### ISSUE TITLE
[BUG] Blockquotes are not rendered as such

### ISSUE THREAD

**Issue by ryadaj** [ivan-lednev/better-search-views#4]
Maybe intentional, but blockquotes don't appear as blockquotes in the search pane.

<img width="1799" alt="Screenshot 2023-07-18 at 13 22 46" src="https://github.com/ivan-lednev/better-search-views/assets/82765301/1ed0b6d7-3dcc-4246-9c3e-c50086ca3339">

**Comment by ryadaj** [comment]
Note also the large margins for blockquotes in the search pane (attached above), compared to other results that are not blockquotes

<img width="415" alt="Screenshot 2023-07-18 at 13 26 02" src="https://github.com/ivan-lednev/better-search-views/assets/82765301/5cd934ba-4209-493e-967c-56176a22af96">

**Comment by ivan-lednev** [comment]
Hello, @ryadaj, 

Thank you for the feedback! There is going to be a fix in the next release.

**Comment by ivan-lednev** [comment]
Please check out 0.1.1 for a fix.

**Comment by ryadaj** [comment]
perfect :) works great!
