### ISSUE TITLE
[Bug] Possible memory leak / Obsidian very sluggish

### ISSUE THREAD

**Issue by StefanoRausch** [ivan-lednev/better-search-views#5]
Suddenly, Obsidian did slow down to an unbearable speed after a while with the plugin enabled.

If I disable the plugin, Obsidian is back to the old glorious days, i.e., it is extremely responsive.

Please check the code, if there is any routine which might cause the high CPU usage.

**Comment by ivan-lednev** [comment]
Hi, @StefanoRausch, thank you for the feedback! Could you specify:
- Did the app slow down after a specific operation, like a search with a lot of matches?
- How long did you use the app after you enabled the plugin and reloaded Obsidian?

**Comment by StefanoRausch** [comment]
I ran Obsidian with your plugin (active) for a few hours and I cannot see any impact performance-wise!

Thank you for looking into it.
