### ISSUE TITLE
[Feature Request] Render images in backlink and search pane

### ISSUE THREAD

**Issue by BruceJLiu** [ivan-lednev/better-search-views#6]
Great job! I'm looking forward to this plugin for a long time. The only missing thing is the images cannot be rendered in the backlink and search pane. Please add this functionality! Thanks for your work!

**Comment by ivan-liadniou-epam** [comment]
Hello, @BruceJLiu, 

I've relied on Obsidian's API to render markdown. I've created an issue in the API repo, you can track it here: https://github.com/obsidianmd/obsidian-api/issues/120

**Comment by seyeeL** [comment]
If an image is too long and exceeds the height of the screen, the context will be lost when scrolling

**Comment by ivan-lednev** [comment]
Added in 0.3.0.
