### ISSUE TITLE
[BUG] Failed to open file (filename). Cant scroll to line

### ISSUE THREAD

**Issue by TonyAtlas** [ivan-lednev/better-search-views#7]
When I start looking for something in a search, it gives me the results correctly.

When I click on one of the results, the note opens, but the place I am looking for where the word is located is not listed.

It gives me an error:

Failed to open file "folder/filename.md"
Cant scroll to line (line number)

This problem was also in previous versions of the plugin.

OS: Windows 10
Obsidian version 1.3.5

**Comment by ivan-lednev** [comment]
Hello, @TonyAtlas,

Thank you for the input! Which file are you trying to open? Is it a regular markdown file? Or is it some special view like Canvas or Kanban?

**Comment by TonyAtlas** [comment]
Thank you for the helpful plugin! 
This happens when I open a regular markdown file.

**Comment by TonyAtlas** [comment]
This happens with any markdown file that has the simplest YAML or no YAML at all. I have tried doing different queries for different notes.

Yes, it always happens. No exceptions. Everything comes up correctly in the search box. But when I want to click on a specific part in the search query to be taken to the right place in the note, this error comes up.

I created an empty file without YAML and wrote one word there. When I tried to open this note with that word in the search, the same error occurred.

Maybe there is a conflict with some plugin. Or do you have any suggestions what else it could be?

**Comment by ivan-lednev** [comment]
If this is a conflict with some other plugin, it's easy enough to know: turn off all other plugins, reload Obsidian and try the behavior that doesn't work. If it helps, turn on plugins one by one and see which one causes it.

This is getting interesting... Let's gather more info:
- What OS do you have?
- What version of Obsidian are you using?
- What version of the plugin are you using?

**Comment by TonyAtlas** [comment]
As I wrote above in the first post

OS: Windows 10
Obsidian version 1.3.5

And your plugin version is 0.2.0
But the same error was also with the previous two versions.

I will check the work with disabled plugins and will share the results with you immediately.

**Comment by TonyAtlas** [comment]
I completely reinstalled Obsidian with all plugins and the problem disappeared. This problem can be closed.

Thank you for your attention and for the plugin.

**Comment by TonyAtlas** [comment]
I completely reinstalled Obsidian with all plugins and the problem disappeared. This problem can be closed.

Thank you for your attention and for the plugin.
